### ISSUE TITLE
Publish to nuget.org?

### ISSUE THREAD

**Issue by DavidRogers** [Vantiv/cnp-sdk-for-dotnet#1]
I would like to upgrade to this version of the sdk and was wondering what your time frame is for publishing this to nuget.org?

**Comment by brianarnold789** [comment]
We released all new versions of the SDK this morning, there are now versions 8.29.5, 9.12.6, and 11.1.1 on NuGet and GitHub

**Comment by DavidRogers** [comment]
@brianarnold789, Sorry, I should have stated that I was looking for v12 to be published to nuget.org.

**Comment by brianarnold789** [comment]
We will be releasing this as soon as we have worked through our build issues and are confident there aren't any hidden problems. Projecting this will be released by 12/8/17

**Comment by brianarnold789** [comment]
release 12.0.0 is completed on Nuget and GitHub
