### ISSUE TITLE
How do I do a receiveFromCnp when the response file name is unknown?

### ISSUE THREAD

**Issue by haricharan** [Vantiv/cnp-sdk-for-dotnet#5]
I am having an issue while consuming the API for Account Updater batch requests through SFTP. With Account Updater batch requests, we get an acknowledgement response and the final response. 

The acknowledgement response has the same batch name as the request, so it's retrievable from SFTP, however I wouldn't know the file name for the final response file.

**Comment by swapnilhande** [comment]
Hi Hari, Please email Implementation@vantiv.com to know what the file name would be. Thanks.
